### ISSUE TITLE
Jump/Snapping items on scroll

### ISSUE THREAD

**Issue by behelit** [lnicolet/HiddenSearchWithRecyclerView#2]
It seems to jump when hiding/showing the searchview.
You can see the items be displaced

**Comment by behelit** [comment]
Touch seems to get offset as well when it's visible

**Comment by lucanicoletti** [comment]
Can you upload a gif showing this issue? Can't reproduce, sorry

**Comment by lucanicoletti** [comment]
Closing this as no feedback was given. Feel free to open it again if facing again this problem.
Thanks.
