### ISSUE TITLE
compatibly of java

### ISSUE THREAD

**Issue by rajam1215** [lnicolet/HiddenSearchWithRecyclerView#4]
Hello @lnicolet 

Please make java compatible so we can use this library in java code for search in recycler view.

Thanks.

**Comment by lucanicoletti** [comment]
Can you be more specific? I tried using the library in a Java project and it's working without any problem.

What error are you encoring? Any logs/errors?

**Comment by rajam1215** [comment]
how can i use your search layout edittext with this code, i try to find this code.

means addTextChangedListener, there is no any option please provide some snippet code.

thanks

//adding a TextChangedListener
        //to call a method whenever there is some change on the EditText
        editTextSearch.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {
 
            }
 
            @Override
            public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
 
            }
 
            @Override
            public void afterTextChanged(Editable editable) {
                //after the change calling the method and passing the search input
                filter(editable.toString());
            }
        });

**Comment by rajam1215** [comment]
Ok thanks, i use this i can use this in my java code as well, but it have some error my be please see.
![Screenshot_20190527-105821 1](https://user-images.githubusercontent.com/16591300/58397433-8fde9e00-806e-11e9-823b-3344664881d5.png)
![Screenshot_20190527-105904 1](https://user-images.githubusercontent.com/16591300/58397438-9836d900-806e-11e9-8107-9e9aadccb1ba.png)

you see in both image unnecessary space between recycler view and search layout how to solve that ,

i need my recycler view according to your example.

my xml coding 

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/viewBg"
    android:orientation="vertical"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context=".activity.ModelsActivity"
    tools:showIn="@layout/activity_models">

    <com.nicolettilu.hiddensearchwithrecyclerview.HiddenSearchWithRecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:filterWhileTyping="true"
        app:hideAtScroll="true"
        app:scrollToBottomBeforeHide="false"
        app:scrollToTopBeforeShow="false"
        app:visibleAtInit="false">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:clipToPadding="false"
            android:scrollbars="vertical" />

    </com.nicolettilu.hiddensearchwithrecyclerview.HiddenSearchWithRecyclerView>

</LinearLayout>

**Comment by rajam1215** [comment]
@lnicolet 
i have solution with your comment, because i don't check in my code once.
Thanks

i close that issue with this solution, that i generate.
