### ISSUE TITLE
Incorrect position of click in RV

### ISSUE THREAD

**Issue by Serg-Shar** [lnicolet/HiddenSearchWithRecyclerView#7]
I have a fork with minor changes to demonstrate the problem:
https://github.com/Serg-Shar/HiddenSearchWithRecyclerView

Case 1: search bar is hidden: 
Click on any item calls click on the selected item:
![Screenshot_2019-08-13-13-55-37-888_com nicolettilu hiddensearchwithrecyclerviewsample](https://user-images.githubusercontent.com/54064375/62936535-bb9e3400-bdd2-11e9-8c95-b53522ab05ef.png)

Case 1: search bar is visible: 
Click on any item calls click on the following one:
![Screenshot_2019-08-13-13-55-44-781_com nicolettilu hiddensearchwithrecyclerviewsample](https://user-images.githubusercontent.com/54064375/62936551-cc4eaa00-bdd2-11e9-8d75-e389eb624bf1.png)

Is it possible to avoid the mismatching independently of scroll bar state?

**Comment by lucanicoletti** [comment]
Have a look a [this](https://github.com/lnicolet/HiddenSearchWithRecyclerView/issues/8). The problem seems the same. I'll update that `issue` from now on.

Thanks for raising it.

**Comment by lucanicoletti** [comment]
This should be fixed with the [0.0.6](https://bintray.com/lnicolet/HiddenSearchWithRecyclerView/HiddenSearchWithRecyclerView/0.0.6) version of the library.

Please confirm and close the issue if it is, or update it.

**Comment by Serg-Shar** [comment]
Thanks for the attention!

Now, close the issue as duplicate (more information in #8)
